# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Actualizaciones para dependencias de Python (pip)
  - package-ecosystem: "pip"
    directory: "/" # Cambia este directorio si tu archivo requirements.txt está en otra carpeta
    schedule:
      interval: "weekly"

  # Actualizaciones para dependencias de Maven
  - package-ecosystem: "maven"
    directory: "/" # Cambia este directorio si tu archivo pom.xml está en otra carpeta
    schedule:
      interval: "weekly"
