package es.cesar.app.web;// Generated by Selenium IDE

import es.cesar.app.config.SeleniumConfig;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit.jupiter.DisabledIf;

import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
@DisabledIf(expression = "#{'coverage'.equals(environment.getProperty('spring.profiles.active'))}")
class TranslationSpanishEnglishTest {
    JavascriptExecutor js;
    private WebDriver driver;

    @BeforeEach
    void setUp() {
        driver = SeleniumConfig.getWebDriver();
        js = (JavascriptExecutor) driver;
    }

    @AfterEach
    void tearDown() {
        driver.quit();
    }

    @Test
    void translationSpanishEnglish() {
        driver.get(SeleniumConfig.url);
        driver.findElement(By.cssSelector("#selectedLang > span")).click();
        driver.findElement(By.cssSelector(".show > li:nth-child(1) span")).click();
        assertEquals("Español", driver.findElement(By.cssSelector("#selectedLang > span")).getText());
        assertEquals("Iniciar sesión", driver.findElement(By.cssSelector(".me-2 > span")).getText());
        assertEquals("Registrarse", driver.findElement(By.cssSelector(".btn:nth-child(2) > span")).getText());
        driver.findElement(By.cssSelector("#selectedLang > span")).click();
        driver.findElement(By.cssSelector(".show > li:nth-child(2) span")).click();
        assertEquals("English", driver.findElement(By.cssSelector("#selectedLang > span")).getText());
        assertEquals("Sign In", driver.findElement(By.linkText("Sign In")).getText());
        assertEquals("Sign Up", driver.findElement(By.cssSelector(".btn:nth-child(2) > span")).getText());
    }
}
