package es.cesar.app.web;// Generated by Selenium IDE

import es.cesar.app.config.SeleniumConfig;
import es.cesar.app.model.User;
import es.cesar.app.service.UserService;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit.jupiter.DisabledIf;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertFalse;

@SpringBootTest
@DisabledIf(expression = "#{'coverage'.equals(environment.getProperty('spring.profiles.active'))}")
class UserCreationLoginTest {

    JavascriptExecutor js;
    String username = "prueba";
    String password = "prueba";
    @Autowired
    UserService userService;
    private WebDriver driver;

    @BeforeEach
    void setUp() {
        driver = SeleniumConfig.getWebDriver();
        js = (JavascriptExecutor) driver;

        User user = userService.getUserByUsername(username);
        if (user != null) {
            userService.deleteUserById(user.getId());
        }
    }

    @AfterEach
    void tearDown() {
        driver.quit();
        User user = userService.getUserByUsername(username);
        if (user != null) {
            userService.deleteUserById(user.getId());
        }
    }

    @Test
    void userCreationLogin() {
        driver.get(SeleniumConfig.url);
        driver.findElement(By.cssSelector(".me-2 > span")).click();
        driver.findElement(By.id("inputUsername")).click();
        driver.findElement(By.id("inputUsername")).sendKeys(username);
        driver.findElement(By.id("inputPassword")).click();
        driver.findElement(By.id("inputPassword")).sendKeys(password);
        driver.findElement(By.cssSelector(".text-center > .btn")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".alert > span"));
            assertFalse(elements.isEmpty());
        }
        driver.findElement(By.cssSelector(".btn-outline-primary > span")).click();
        driver.findElement(By.id("inputUsername")).click();
        driver.findElement(By.id("inputUsername")).sendKeys(username);
        driver.findElement(By.id("inputPassword")).sendKeys(password);
        driver.findElement(By.cssSelector(".btn-primary:nth-child(1)")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".alert > span"));
            assertFalse(elements.isEmpty());
        }
        driver.findElement(By.id("inputUsername")).sendKeys(username);
        driver.findElement(By.id("inputPassword")).sendKeys(password);
        driver.findElement(By.cssSelector(".text-center > .btn")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".mb-5"));
            assertFalse(elements.isEmpty());
        }
    }
}