name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FILE_NAME: memoria  # Nombre del archivo sin extensión

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Mantiene credenciales para hacer push

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ env.FILE_NAME }}.tex
          workdir: docs  # Indica que el LaTeX se ejecuta dentro de 'docs'
          output_directory: docs  # Asegura que el PDF salga en 'docs/'

      - name: Move PDF
        run: |
          mkdir -p docs/pdf
          mv docs/${{ env.FILE_NAME }}.pdf docs/pdf/${{ env.FILE_NAME }}.pdf

      - name: Commit and push PDF
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/pdf/${{ env.FILE_NAME }}.pdf
          git diff --staged --quiet || (git commit -m "Update compiled ${{ env.FILE_NAME }}.pdf" && git push)
