name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FILE_NAME: memoria  # Nombre del archivo sin extensión
      OUT_DIR: docs/pdf
      WORK_DIR: docs

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Mantiene credenciales para hacer push

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ env.FILE_NAME }}.tex
          working_directory: ${{ env.WORK_DIR }}/
      - name: Move PDF to ${{ env.OUT_DIR }}
        run: |
          mkdir -p ${{ env.OUT_DIR }}
          mv ${{ env.WORK_DIR }}/${{ env.FILE_NAME }}.pdf ${{ env.OUT_DIR }}/${{ env.FILE_NAME }}.pdf

      - name: Commit and push PDF
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ env.OUT_DIR }}/${{ env.FILE_NAME }}.pdf
          git diff --staged --quiet || (git commit -m "Update compiled ${{ env.FILE_NAME }}.pdf" && git push)
