name: LaTeX to PDF and Push

on:
  push:
    paths:
      - '**/*.tex' # Ejecuta la acción solo si se modifica un archivo .tex
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Configura el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Paso 2: Instala LaTeX
    - name: Install TeX Live
      run: sudo apt-get update && sudo apt-get install -y texlive-full

    # Paso 3: Compila el archivo .tex a PDF
    - name: Compile LaTeX document
      run: |
        mkdir -p output
        latexmk -pdf -output-directory=output your-document.tex
      working-directory: ./ # Cambia este directorio si tu archivo .tex está en un subdirectorio

    # Paso 4: Copia el PDF al repositorio
    - name: Move PDF to repository
      run: |
        mv output/your-document.pdf ./compiled/
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add compiled/your-document.pdf
        git commit -m "Add compiled PDF [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
