name: LaTeX to PDF and Push

on:
  push:
    paths:
      - '**/*.tex' # Solo se ejecuta cuando se modifica un archivo .tex
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    container:
      image: danteev/texlive:latest # Imagen Docker con LaTeX preinstalado

    steps:
    # Paso 1: Configura el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # NEW STEP: Configure safe directory
    - name: Configure safe directory
      run: git config --global --add safe.directory /__w/PruebasTFG/PruebasTFG

    # Paso 2: Encuentra y compila los archivos modificados
    - name: Find and Compile LaTeX Files
      run: |
        mkdir -p compiled
        for file in $(git diff --name-only HEAD^ HEAD | grep '.tex$'); do
          latexmk -pdf -output-directory=compiled $file
        done

    # Paso 3: Realiza el commit y push de los PDFs generados
    - name: Push Compiled PDFs
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add compiled/*.pdf
        git commit -m "Add compiled PDFs for modified LaTeX files [skip ci]" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
