name: Generate PDFs form LaTex

on:
  push:
    branches:
      - main   
    paths:
      - 'docs/source/**'        
      - '!docs/pdf/**'   
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FILE_NAME: memoria  
      FILE_NAME2: anexos 
      OUT_DIR: docs/pdfs
      WORK_DIR: docs/source

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            ${{ env.FILE_NAME }}.tex
            ${{ env.FILE_NAME2 }}.tex
          working_directory: ${{ env.WORK_DIR }}/
      - name: Move PDF to ${{ env.OUT_DIR }}
        run: |
          mkdir -p ${{ env.OUT_DIR }}
          mv ${{ env.WORK_DIR }}/${{ env.FILE_NAME }}.pdf ${{ env.OUT_DIR }}/${{ env.FILE_NAME }}.pdf
          mv ${{ env.WORK_DIR }}/${{ env.FILE_NAME2 }}.pdf ${{ env.OUT_DIR }}/${{ env.FILE_NAME2 }}.pdf

      - name: Commit and push PDF
        run: |
          git config --global user.name "Automated PDF Generator GitHub Actions"
          git config --global user.email "pdf-generator[bot]@users.noreply.github.com"
          git add ${{ env.OUT_DIR }}/${{ env.FILE_NAME }}.pdf ${{ env.OUT_DIR }}/${{ env.FILE_NAME2 }}.pdf 
          git diff --staged --quiet || (git commit -m "Update compiled ${{ env.FILE_NAME }}.pdf and ${{ env.FILE_NAME2 }}.pdf" && git push)
