
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true # Asegura que las credenciales de GitHub se mantengan

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: memoria.tex

      - name: Commit and push PDF
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add memoria.pdf
          git commit -m "Update compiled memoria.pdf"
          git push
